echo "DurationWalkingForPleasure"
echo "250"
echo "replication with discovery `bedtools intersect -wa -a locus.250000.DurationWalkingForPleasure.discovery.bed -b locus.250000.DurationWalkingForPleasure.replication.bed | sort |  uniq | wc -l`"
echo "discovery total: `bedtools sort -i locus.250000.DurationWalkingForPleasure.discovery.bed | uniq | wc -l`"
echo "replication total:` bedtools sort -i locus.250000.DurationWalkingForPleasure.replication.bed | uniq | wc -l`"
echo "discovery with replication: `bedtools intersect -wa -a locus.250000.DurationWalkingForPleasure.replication.bed -b locus.250000.DurationWalkingForPleasure.discovery.bed | sort | uniq | wc -l`"
echo "DurationWalkingForPleasure"
echo "500"
echo "replication with discovery `bedtools intersect -wa -a locus.500000.DurationWalkingForPleasure.discovery.bed -b locus.500000.DurationWalkingForPleasure.replication.bed | sort |  uniq | wc -l`"
echo "discovery total: `bedtools sort -i locus.500000.DurationWalkingForPleasure.discovery.bed | uniq | wc -l`"
echo "replication total:` bedtools sort -i locus.500000.DurationWalkingForPleasure.replication.bed | uniq | wc -l`"
echo "discovery with replication: `bedtools intersect -wa -a locus.500000.DurationWalkingForPleasure.replication.bed -b locus.500000.DurationWalkingForPleasure.discovery.bed | sort | uniq | wc -l`"


echo "TimeSpentOutdoors"
echo "250"
echo "replication with discovery `bedtools intersect -wa -a locus.250000.TimeSpentOutdoors.discovery.bed -b locus.250000.TimeSpentOutdoors.replication.bed | sort |  uniq | wc -l`"
echo "discovery total: `bedtools sort -i locus.250000.TimeSpentOutdoors.discovery.bed | uniq | wc -l`"
echo "replication total:` bedtools sort -i locus.250000.TimeSpentOutdoors.replication.bed | uniq | wc -l`"
echo "discovery with replication: `bedtools intersect -wa -a locus.250000.TimeSpentOutdoors.replication.bed -b locus.250000.TimeSpentOutdoors.discovery.bed | sort | uniq | wc -l`"
echo "TimeSpentOutdoors"
echo "500"
echo "replication with discovery `bedtools intersect -wa -a locus.500000.TimeSpentOutdoors.discovery.bed -b locus.500000.TimeSpentOutdoors.replication.bed | sort |  uniq | wc -l`"
echo "discovery total: `bedtools sort -i locus.500000.TimeSpentOutdoors.discovery.bed | uniq | wc -l`"
echo "replication total:` bedtools sort -i locus.500000.TimeSpentOutdoors.replication.bed | uniq | wc -l`"
echo "discovery with replication: `bedtools intersect -wa -a locus.500000.TimeSpentOutdoors.replication.bed -b locus.500000.TimeSpentOutdoors.discovery.bed | sort | uniq | wc -l`"


echo "OverallAccelerationAverage"
echo "250"
echo "replication with discovery `bedtools intersect -wa -a locus.250000.OverallAccelerationAverage.discovery.bed -b locus.250000.OverallAccelerationAverage.replication.bed | sort |  uniq | wc -l`"
echo "discovery total: `bedtools sort -i locus.250000.OverallAccelerationAverage.discovery.bed | uniq | wc -l`"
echo "replication total:` bedtools sort -i locus.250000.OverallAccelerationAverage.replication.bed | uniq | wc -l`"
echo "discovery with replication: `bedtools intersect -wa -a locus.250000.OverallAccelerationAverage.replication.bed -b locus.250000.OverallAccelerationAverage.discovery.bed | sort | uniq | wc -l`"
echo "OverallAccelerationAverage"
echo "500"
echo "replication with discovery `bedtools intersect -wa -a locus.500000.OverallAccelerationAverage.discovery.bed -b locus.500000.OverallAccelerationAverage.replication.bed | sort |  uniq | wc -l`"
echo "discovery total: `bedtools sort -i locus.500000.OverallAccelerationAverage.discovery.bed | uniq | wc -l`"
echo "replication total:` bedtools sort -i locus.500000.OverallAccelerationAverage.replication.bed | uniq | wc -l`"
echo "discovery with replication: `bedtools intersect -wa -a locus.500000.OverallAccelerationAverage.replication.bed -b locus.500000.OverallAccelerationAverage.discovery.bed | sort | uniq | wc -l`"
